-- MySQL Script generated by MySQL Workbench
-- Wed Jun  3 16:23:32 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema footballclub
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `footballclub` ;

-- -----------------------------------------------------
-- Schema footballclub
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `footballclub` DEFAULT CHARACTER SET utf8 ;
USE `footballclub` ;

-- -----------------------------------------------------
-- Table `footballclub`.`ROLE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `footballclub`.`ROLE` ;

CREATE TABLE IF NOT EXISTS `footballclub`.`ROLE` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `CREATED_AT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_AT` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `NAME` VARCHAR(13) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `NAME_UNIQUE` (`NAME` ASC));


-- -----------------------------------------------------
-- Table `footballclub`.`USER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `footballclub`.`USER` ;

CREATE TABLE IF NOT EXISTS `footballclub`.`USER` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `CREATED_AT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_AT` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `FIRSTNAME` VARCHAR(21) NOT NULL,
  `LASTNAME` VARCHAR(24) NOT NULL,
  `DATE_OF_BIRTH` DATE NOT NULL,
  `DESCRIPTION` TEXT NULL,
  `PICTURE` VARCHAR(28) NULL,
  `EMAIL` VARCHAR(62) NOT NULL,
  `PASSWORD` VARCHAR(60) NOT NULL,
  `ROLE_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_USER_ROLE1_idx` (`ROLE_ID` ASC),
  UNIQUE INDEX `EMAIL_UNIQUE` (`EMAIL` ASC),
  CONSTRAINT `fk_USER_ROLE1`
    FOREIGN KEY (`ROLE_ID`)
    REFERENCES `footballclub`.`ROLE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `footballclub`.`FUNCTION_FCH`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `footballclub`.`FUNCTION_FCH` ;

CREATE TABLE IF NOT EXISTS `footballclub`.`FUNCTION_FCH` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `CREATED_AT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_AT` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `NAME` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `NAME_UNIQUE` (`NAME` ASC));


-- -----------------------------------------------------
-- Table `footballclub`.`MEMBER_HISTORY`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `footballclub`.`MEMBER_HISTORY` ;

CREATE TABLE IF NOT EXISTS `footballclub`.`MEMBER_HISTORY` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `CREATED_AT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_AT` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `START_DATE` DATE NOT NULL,
  `END_DATE` DATE NULL,
  `MEMBER_ID` INT NOT NULL,
  `FUNCTION_FCH_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_MEMBER_HISTORY_MEMBER1_idx` (`MEMBER_ID` ASC),
  INDEX `fk_MEMBER_HISTORY_FUNCTION_FSR1_idx` (`FUNCTION_FCH_ID` ASC),
  CONSTRAINT `fk_MEMBER_HISTORY_MEMBER1`
    FOREIGN KEY (`MEMBER_ID`)
    REFERENCES `footballclub`.`USER` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MEMBER_HISTORY_FUNCTION_FSR1`
    FOREIGN KEY (`FUNCTION_FCH_ID`)
    REFERENCES `footballclub`.`FUNCTION_FCH` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

USE `footballclub` ;

-- -----------------------------------------------------
-- Placeholder table for view `footballclub`.`getUserMemberHistory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `footballclub`.`getUserMemberHistory` (`ID` INT, `START_DATE` INT, `END_DATE` INT, `MEMBER_ID` INT, `FUNCTION_FCH_ID` INT, `FIRSTNAME` INT, `LASTNAME` INT, `DATE_OF_BIRTH` INT, `DESCRIPTION` INT, `PICTURE` INT, `EMAIL` INT, `ROLE_ID` INT);

-- -----------------------------------------------------
-- View `footballclub`.`getUserMemberHistory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `footballclub`.`getUserMemberHistory`;
DROP VIEW IF EXISTS `footballclub`.`getUserMemberHistory` ;
USE `footballclub`;
CREATE 
     OR REPLACE DEFINER = root@localhost
VIEW footballclub.getUserMemberHistory AS
    SELECT 
        `mh`.`ID` AS `ID`,
        `mh`.`START_DATE` AS `START_DATE`,
        `mh`.`END_DATE` AS `END_DATE`,
        `mh`.`MEMBER_ID` AS `MEMBER_ID`,
        `mh`.`FUNCTION_FCH_ID` AS `FUNCTION_FCH_ID`,
        `u`.`FIRSTNAME` AS `FIRSTNAME`,
        `u`.`LASTNAME` AS `LASTNAME`,
        `u`.`DATE_OF_BIRTH` AS `DATE_OF_BIRTH`,
        `u`.`DESCRIPTION` AS `DESCRIPTION`,
        `u`.`PICTURE` AS `PICTURE`,
        `u`.`EMAIL` AS `EMAIL`,
        `u`.`ROLE_ID` AS `ROLE_ID`
    FROM
        (`footballclub`.`MEMBER_HISTORY` `mh`
        JOIN `footballclub`.`USER` `u` ON ((`mh`.`MEMBER_ID` = `u`.`ID`)));

-- -----------------------------------------------------
-- Data for table `footballclub`.`ROLE`
-- -----------------------------------------------------
START TRANSACTION;
USE `footballclub`;
INSERT INTO `footballclub`.`ROLE` (`ID`, `CREATED_AT`, `UPDATED_AT`, `NAME`) VALUES (DEFAULT, DEFAULT, NULL, 'Administrator');
INSERT INTO `footballclub`.`ROLE` (`ID`, `CREATED_AT`, `UPDATED_AT`, `NAME`) VALUES (DEFAULT, DEFAULT, NULL, 'Mitglied');
INSERT INTO `footballclub`.`ROLE` (`ID`, `CREATED_AT`, `UPDATED_AT`, `NAME`) VALUES (DEFAULT, DEFAULT, NULL, 'Nutzer');

COMMIT;


-- -----------------------------------------------------
-- Data for table `footballclub`.`USER`
-- -----------------------------------------------------
START TRANSACTION;
USE `footballclub`;
INSERT INTO `footballclub`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Celine', 'FCH', '1998-12-16', 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.', 'profil1.jpg', 'celine@fch.de', '$2y$13$bJdi31tD.4E4sfvK9nCCS.SaPXEHb0QrO2aBGDZ/zwgj.031CUTMy', 1);
INSERT INTO `footballclub`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Anastasia', 'FCH', '1997-04-17', 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.', 'profil2.jpg', 'anastasia@fch.de', '$2y$13$bJdi31tD.4E4sfvK9nCCS.SaPXEHb0QrO2aBGDZ/zwgj.031CUTMy', 1);
INSERT INTO `footballclub`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Admin', 'FCH', '1986-04-01', 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.', 'profil5.jpg', 'admin@fch.de', '$2y$13$bJdi31tD.4E4sfvK9nCCS.SaPXEHb0QrO2aBGDZ/zwgj.031CUTMy', 1);
INSERT INTO `footballclub`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Mitglied', 'FCH', '1993-07-12', 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.', 'profil6.jpg', 'mitglied@fch.de', '$2y$13$bJdi31tD.4E4sfvK9nCCS.SaPXEHb0QrO2aBGDZ/zwgj.031CUTMy', 2);
INSERT INTO `footballclub`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Nutzer', 'FCH', '1996-08-27', 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.', 'profil7.jpg', 'nutzer@fch.de', '$2y$13$bJdi31tD.4E4sfvK9nCCS.SaPXEHb0QrO2aBGDZ/zwgj.031CUTMy', 3);
INSERT INTO `footballclub`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Marie ', 'Mueller', '1991-01-28', 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.', 'profil8.jpg', 'marie.mueller@fch.de', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 2);
INSERT INTO `footballclub`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Lukas ', 'Meister', '1996-01-10', 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.', 'profil9.jpg', 'lukas.meister@fch.de', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 2);
INSERT INTO `footballclub`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Marcel', 'Kaiser', '1991-10-09', 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.', 'profil10.jpg', 'marcel.kaiser@fch.de', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 2);
INSERT INTO `footballclub`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Winter', 'Lamb', '1993-06-07', NULL, NULL, 'egestas.ligula@at.edu', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `footballclub`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Joseph', 'Cooper', '1987-05-31', NULL, NULL, 'In.condimentum.Donec@turpis.org', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `footballclub`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Moana', 'Mccoy', '2000-05-21', NULL, NULL, 'Aliquam@eusemPellentesque.ca', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `footballclub`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Walker', 'Molina', '1989-03-02', NULL, NULL, 'orci.tincidunt.adipiscing@anteiaculis.net', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `footballclub`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Carly', 'Jensen', '1992-11-19', NULL, NULL, 'interdum.Sed@necquamCurabitur.ca', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `footballclub`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'McKenzie', 'Cunningham', '1994-03-19', NULL, NULL, 'vestibulum.massa.rutrum@felis.edu', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `footballclub`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Celeste', 'Mcneil', '2004-07-22', NULL, NULL, 'ut@sed.co.uk', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `footballclub`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Fiona', 'Conrad', '2000-02-01', NULL, NULL, 'sit@vestibulumnequesed.com', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `footballclub`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Harlan', 'Cannon', '1988-11-21', NULL, NULL, 'egestas.Aliquam@vulputate.com', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `footballclub`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Ronan', 'Wall', '1986-01-24', NULL, NULL, 'molestie@idliberoDonec.ca', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `footballclub`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Zephr', 'Marks', '1998-04-13', NULL, NULL, 'sit.amet@scelerisquescelerisque.net', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `footballclub`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Hakeem', 'Carlson', '2001-12-24', NULL, NULL, 'hendrerit.neque@neque.org', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `footballclub`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Cailin', 'Carney', '1996-12-30', NULL, NULL, 'accumsan.interdum.libero@etarcu.net', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `footballclub`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Abigail', 'Lynn', '1992-12-21', NULL, NULL, 'convallis.erat@molestie.net', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `footballclub`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Amir', 'Vasquez', '2001-08-31', NULL, NULL, 'mattis.velit.justo@Aenean.ca', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `footballclub`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Giacomo', 'Rogers', '1989-05-29', NULL, NULL, 'tristique.ac@malesuadafamesac.com', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `footballclub`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Colby', 'Barnes', '2004-09-15', NULL, NULL, 'Cras.vehicula@viverraDonectempus.co.uk', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `footballclub`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Octavia', 'Walter', '2003-06-05', NULL, NULL, 'Etiam@magna.com', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `footballclub`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Scarlett', 'Knight', '1995-04-16', NULL, NULL, 'pede.Cras@mus.net', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `footballclub`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Kirby', 'Trujillo', '2004-02-11', NULL, NULL, 'fringilla@tinciduntDonecvitae.ca', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `footballclub`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Kyra', 'Frye', '1985-01-19', NULL, NULL, 'Curae.Donec.tincidunt@risus.net', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `footballclub`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Lois', 'Molina', '1990-08-20', NULL, NULL, 'aliquet.sem.ut@velesttempor.co.uk', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `footballclub`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Amal', 'Suarez', '2003-02-09', NULL, NULL, 'vehicula.Pellentesque@Vestibulumante.net', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `footballclub`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Whoopi', 'Wiggins', '1991-07-27', NULL, NULL, 'dolor.elit.pellentesque@condimentumegetvolutpat.ca', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `footballclub`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Finn', 'Miranda', '1984-06-27', NULL, NULL, 'diam.lorem@pellentesque.net', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `footballclub`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Elmo', 'Neal', '1987-06-12', NULL, NULL, 'eu.erat@Sed.edu', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `footballclub`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Phillip', 'Stokes', '2003-12-02', NULL, NULL, 'mollis.nec@Vestibulumanteipsum.ca', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `footballclub`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Tanya', 'Wooten', '1995-05-23', NULL, NULL, 'sociis.natoque@Suspendissealiquet.net', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `footballclub`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Rhoda', 'Gibbs', '1994-10-30', NULL, NULL, 'elit.pharetra@porttitortellus.edu', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `footballclub`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Malachi', 'Cross', '2004-11-21', NULL, NULL, 'aliquet@Sed.co.uk', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `footballclub`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Aline', 'Henson', '2001-03-12', NULL, NULL, 'vel.venenatis.vel@placeratCrasdictum.ca', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `footballclub`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Maryam', 'Osborne', '1997-03-04', NULL, NULL, 'in@purus.ca', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `footballclub`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Bradley', 'Delacruz', '1987-01-26', NULL, NULL, 'Integer@ullamcorper.org', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `footballclub`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Joshua', 'Finch', '1986-03-10', NULL, NULL, 'massa.lobortis.ultrices@nectempusscelerisque.ca', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `footballclub`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Graiden', 'Wilkinson', '1990-03-08', NULL, NULL, 'montes.nascetur@Donec.co.uk', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `footballclub`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Vera', 'Wright', '1990-11-18', NULL, NULL, 'Phasellus.dolor@sit.edu', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `footballclub`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Jenna', 'Valenzuela', '1990-10-10', NULL, NULL, 'est.Mauris.eu@fringilla.com', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `footballclub`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Moana', 'Gonzales', '1997-07-19', NULL, NULL, 'eu@egestasascelerisque.edu', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `footballclub`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Rafael', 'Arnold', '2005-09-30', NULL, NULL, 'magna.a@neque.ca', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `footballclub`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Maggie', 'Wallace', '1997-01-31', NULL, NULL, 'erat@non.co.uk', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `footballclub`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Dominique', 'Roman', '2001-04-24', NULL, NULL, 'tortor.nibh@Naminterdumenim.org', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `footballclub`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Merritt', 'Olsen', '1997-01-09', NULL, NULL, 'Nunc.quis@In.ca', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `footballclub`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Wing', 'Foster', '1984-03-30', NULL, NULL, 'quis.diam@iaculis.ca', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `footballclub`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Dustin', 'Decker', '2002-04-16', NULL, NULL, 'a.enim@lobortisauguescelerisque.org', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `footballclub`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Orlando', 'Barr', '1986-06-11', NULL, NULL, 'Nullam.enim@ipsumnuncid.edu', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `footballclub`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Emerson', 'Parsons', '1997-08-16', NULL, NULL, 'Curae.Phasellus@nequesed.edu', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `footballclub`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Kimberly', 'Lyons', '1989-08-02', NULL, NULL, 'malesuada@antedictummi.ca', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `footballclub`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Benjamin', 'Gillespie', '1998-11-21', NULL, NULL, 'sed@sem.com', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `footballclub`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Brandon', 'Rodgers', '1993-11-29', NULL, NULL, 'sit.amet@feugiat.org', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `footballclub`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Aretha', 'Casey', '1991-09-17', NULL, NULL, 'turpis.vitae.purus@aliquetsem.co.uk', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `footballclub`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Catherine', 'Summers', '1990-07-04', NULL, NULL, 'et@sem.net', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `footballclub`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Lillith', 'Whitney', '1984-02-18', NULL, NULL, 'Nunc@eleifendCrassed.edu', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `footballclub`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Craig', 'Banks', '1992-09-01', NULL, NULL, 'in.dolor@sitametfaucibus.org', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `footballclub`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Ignatius', 'Parrish', '1993-04-02', NULL, NULL, 'pellentesque.massa@luctus.net', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `footballclub`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Bethany', 'Donaldson', '1991-03-20', NULL, NULL, 'ultrices@arcuVestibulumut.ca', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `footballclub`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Grace', 'Weeks', '1997-11-12', NULL, NULL, 'Maecenas.malesuada.fringilla@montesnascetur.edu', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `footballclub`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Marcia', 'Wise', '1986-03-20', NULL, NULL, 'tellus.lorem@eratnequenon.co.uk', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `footballclub`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Frances', 'Blair', '1993-08-18', NULL, NULL, 'Sed.nulla@felisDonectempor.net', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `footballclub`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Athena', 'Crane', '1988-04-23', NULL, NULL, 'sit.amet.risus@feugiatplaceratvelit.ca', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `footballclub`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Joshua', 'Moody', '1987-05-07', NULL, NULL, 'ante.dictum.mi@Vestibulumanteipsum.co.uk', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `footballclub`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Jessamine', 'Slater', '1993-08-23', NULL, NULL, 'urna@semutcursus.net', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `footballclub`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Grady', 'Mcdaniel', '2004-08-22', NULL, NULL, 'felis.adipiscing@inaliquet.com', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `footballclub`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Camille', 'Carver', '1997-05-18', NULL, NULL, 'a@Cumsociis.edu', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `footballclub`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Noelle', 'Parrish', '1995-10-20', NULL, NULL, 'non@erat.ca', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `footballclub`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'April', 'Middleton', '1988-02-20', NULL, NULL, 'purus.mauris.a@nislNullaeu.ca', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `footballclub`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Gray', 'Casey', '1987-11-22', NULL, NULL, 'molestie@sapien.com', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `footballclub`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Myles', 'Bender', '1998-12-14', NULL, NULL, 'malesuada.fames@eleifendnondapibus.com', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `footballclub`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Kasper', 'Rogers', '1986-01-12', NULL, NULL, 'ligula.Aenean.euismod@molestieSedid.net', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `footballclub`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Kareem', 'Hickman', '1991-10-30', NULL, NULL, 'neque.pellentesque.massa@litoratorquentper.edu', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `footballclub`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Silas', 'Barber', '1992-12-24', NULL, NULL, 'vitae@sed.ca', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `footballclub`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Indigo', 'Carlson', '1997-12-04', NULL, NULL, 'sed.tortor@Sed.net', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `footballclub`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Stewart', 'Flores', '1984-12-13', NULL, NULL, 'interdum@Pellentesquehabitant.net', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `footballclub`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Karyn', 'Murray', '2002-10-07', NULL, NULL, 'tempor@ataugueid.edu', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `footballclub`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Rana', 'Hodge', '1985-10-20', NULL, NULL, 'eget.mollis.lectus@Sednulla.net', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `footballclub`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Byron', 'Dillon', '1991-10-29', NULL, NULL, 'ipsum.primis.in@euligulaAenean.co.uk', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `footballclub`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Maxwell', 'Puckett', '1992-03-24', NULL, NULL, 'massa@malesuada.ca', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `footballclub`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Stewart', 'Zamora', '1997-09-23', NULL, NULL, 'eu.sem.Pellentesque@faucibus.co.uk', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `footballclub`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Kitra', 'Cochran', '1997-01-17', NULL, NULL, 'mus@Maecenas.net', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `footballclub`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Lois', 'Blake', '1989-10-09', NULL, NULL, 'auctor.vitae.aliquet@Vivamus.co.uk', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `footballclub`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Cecilia', 'Nolan', '1988-09-01', NULL, NULL, 'aliquet@Suspendisse.edu', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `footballclub`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Uta', 'Juarez', '1989-09-08', NULL, NULL, 'Sed.pharetra.felis@in.co.uk', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `footballclub`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Dahlia', 'Walsh', '2005-03-26', NULL, NULL, 'pharetra.Nam@Phasellus.org', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `footballclub`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Felix', 'Monroe', '1986-08-09', NULL, NULL, 'eu.elit@eueuismod.org', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `footballclub`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Sylvester', 'Adkins', '2001-01-05', NULL, NULL, 'erat@turpisegestas.org', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `footballclub`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Maxwell', 'Kane', '2003-05-13', NULL, NULL, 'cursus@inmagna.ca', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `footballclub`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Sylvester', 'Clarke', '1990-07-27', NULL, NULL, 'sem.ut@vitaemaurissit.co.uk', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `footballclub`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Diana', 'Parrish', '2001-07-19', NULL, NULL, 'risus@necmollis.com', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `footballclub`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Kyle', 'Levine', '1992-02-29', NULL, NULL, 'risus@aliquamadipiscing.com', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `footballclub`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Jin', 'Gross', '1984-05-12', NULL, NULL, 'mollis@Duis.ca', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `footballclub`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Bert', 'Kent', '1998-09-22', NULL, NULL, 'Nunc.laoreet.lectus@aaliquet.org', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `footballclub`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Shafira', 'Park', '1992-02-02', NULL, NULL, 'id@pede.edu', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `footballclub`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Timothy', 'Charles', '2004-04-29', NULL, NULL, 'sem@porttitor.co.uk', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `footballclub`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Summer', 'Santiago', '1997-05-29', NULL, NULL, 'arcu@tristique.edu', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `footballclub`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Lionel', 'Barrera', '2000-03-26', NULL, NULL, 'risus@dis.com', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `footballclub`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Thaddeus', 'Roth', '2004-06-04', NULL, NULL, 'at.nisi.Cum@dui.org', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `footballclub`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Rylee', 'Robertson', '1992-08-07', NULL, NULL, 'nonummy.ipsum.non@viverra.edu', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);
INSERT INTO `footballclub`.`USER` (`ID`, `CREATED_AT`, `UPDATED_AT`, `FIRSTNAME`, `LASTNAME`, `DATE_OF_BIRTH`, `DESCRIPTION`, `PICTURE`, `EMAIL`, `PASSWORD`, `ROLE_ID`) VALUES (DEFAULT, DEFAULT, NULL, 'Brenna', 'Roy', '1990-10-14', NULL, NULL, 'est@ut.edu', '$2y$13$DOnSoL6TvqCybutTEHUjMuXopthlrIxUYe2VL04Zpz59qk.Mh8uKy', 3);

COMMIT;


-- -----------------------------------------------------
-- Data for table `footballclub`.`FUNCTION_FCH`
-- -----------------------------------------------------
START TRANSACTION;
USE `footballclub`;
INSERT INTO `footballclub`.`FUNCTION_FCH` (`ID`, `CREATED_AT`, `UPDATED_AT`, `NAME`) VALUES (DEFAULT, DEFAULT, NULL, 'Präsident-/in');
INSERT INTO `footballclub`.`FUNCTION_FCH` (`ID`, `CREATED_AT`, `UPDATED_AT`, `NAME`) VALUES (DEFAULT, DEFAULT, NULL, 'Finanzer');
INSERT INTO `footballclub`.`FUNCTION_FCH` (`ID`, `CREATED_AT`, `UPDATED_AT`, `NAME`) VALUES (DEFAULT, DEFAULT, NULL, 'Trainer');
INSERT INTO `footballclub`.`FUNCTION_FCH` (`ID`, `CREATED_AT`, `UPDATED_AT`, `NAME`) VALUES (DEFAULT, DEFAULT, NULL, 'Spieler');
INSERT INTO `footballclub`.`FUNCTION_FCH` (`ID`, `CREATED_AT`, `UPDATED_AT`, `NAME`) VALUES (DEFAULT, DEFAULT, NULL, 'Seniorspieler');
INSERT INTO `footballclub`.`FUNCTION_FCH` (`ID`, `CREATED_AT`, `UPDATED_AT`, `NAME`) VALUES (DEFAULT, DEFAULT, NULL, 'inaktives Mitglied');

COMMIT;


-- -----------------------------------------------------
-- Data for table `footballclub`.`MEMBER_HISTORY`
-- -----------------------------------------------------
START TRANSACTION;
USE `footballclub`;
INSERT INTO `footballclub`.`MEMBER_HISTORY` (`ID`, `CREATED_AT`, `UPDATED_AT`, `START_DATE`, `END_DATE`, `MEMBER_ID`, `FUNCTION_FCH_ID`) VALUES (DEFAULT, DEFAULT, NULL, '2019-01-01', NULL, 1, 1);
INSERT INTO `footballclub`.`MEMBER_HISTORY` (`ID`, `CREATED_AT`, `UPDATED_AT`, `START_DATE`, `END_DATE`, `MEMBER_ID`, `FUNCTION_FCH_ID`) VALUES (DEFAULT, DEFAULT, NULL, '2019-01-01', NULL, 2, 2);
INSERT INTO `footballclub`.`MEMBER_HISTORY` (`ID`, `CREATED_AT`, `UPDATED_AT`, `START_DATE`, `END_DATE`, `MEMBER_ID`, `FUNCTION_FCH_ID`) VALUES (DEFAULT, DEFAULT, NULL, '2019-01-01', '2019-06-01', 3, 5);
INSERT INTO `footballclub`.`MEMBER_HISTORY` (`ID`, `CREATED_AT`, `UPDATED_AT`, `START_DATE`, `END_DATE`, `MEMBER_ID`, `FUNCTION_FCH_ID`) VALUES (DEFAULT, DEFAULT, NULL, '2019-06-02', NULL, 3, 2);
INSERT INTO `footballclub`.`MEMBER_HISTORY` (`ID`, `CREATED_AT`, `UPDATED_AT`, `START_DATE`, `END_DATE`, `MEMBER_ID`, `FUNCTION_FCH_ID`) VALUES (DEFAULT, DEFAULT, NULL, '2019-06-02', NULL, 4, 4);
INSERT INTO `footballclub`.`MEMBER_HISTORY` (`ID`, `CREATED_AT`, `UPDATED_AT`, `START_DATE`, `END_DATE`, `MEMBER_ID`, `FUNCTION_FCH_ID`) VALUES (DEFAULT, DEFAULT, NULL, '2019-06-02', NULL, 6, 3);
INSERT INTO `footballclub`.`MEMBER_HISTORY` (`ID`, `CREATED_AT`, `UPDATED_AT`, `START_DATE`, `END_DATE`, `MEMBER_ID`, `FUNCTION_FCH_ID`) VALUES (DEFAULT, DEFAULT, NULL, '2019-06-02', NULL, 5, 5);
INSERT INTO `footballclub`.`MEMBER_HISTORY` (`ID`, `CREATED_AT`, `UPDATED_AT`, `START_DATE`, `END_DATE`, `MEMBER_ID`, `FUNCTION_FCH_ID`) VALUES (DEFAULT, DEFAULT, NULL, '2019-06-02', NULL, 7, 5);
INSERT INTO `footballclub`.`MEMBER_HISTORY` (`ID`, `CREATED_AT`, `UPDATED_AT`, `START_DATE`, `END_DATE`, `MEMBER_ID`, `FUNCTION_FCH_ID`) VALUES (DEFAULT, DEFAULT, NULL, '2019-06-02', NULL, 8, 5);

COMMIT;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
